syntax on
filetype plugin indent on
set laststatus=0
set ruler
set wildmenu
set background=dark
" map q :q<ENTER>
" map w :w<ENTER>
nnoremap <space> mp`p<c-d>
map spy :setlocal spell spelllang=en_us
map spn :setlocal nospell
" :let g:NERDTreeWinSize=16
" let NERDTreeShowHidden=1
" :nnoremap <C-n> :NERDTreeToggle<CR>
autocmd BufEnter *.md colorscheme gruvbox
autocmd BufEnter *.md setlocal spell spelllang=en_us
" autocmd BufEnter *.css set tabstop=2
" autocmd BufEnter *.css set shiftwidth=2
" autocmd BufEnter *.html set tabstop=2
" autocmd BufEnter *.html set shiftwidth=2
autocmd BufEnter *.py colorscheme gruvbox
autocmd BufEnter *.py set number
" autocmd BufEnter *.py set numberwidth=1
autocmd BufEnter *.py set relativenumber
colorscheme camo
colorscheme substrata
set noswapfile
" set cursorline
" set undofile
" set undodir=~/.vim/undodir
" set ls=2
